#!/bin/bash

# Show where I'm copying
alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"

# Shortcuts
alias g="git"
alias backupvim="cp ~/.vimrc ~/.vimrc.full; cp ~/.vimrc ~/.vimrc.full.backup"
alias incstack="ulimit -s unlimited"
alias redis-cli="~/Tools/redis/redis-3.0.6/src/redis-cli"

# Jump to directories
alias cf="cd /home/rr/Code/CF" #; cp ~/.vimrc.min ~/.vimrc"
alias tc="cd /home/rr/Code/Topcoder; cp ~/.vimrc.full ~/.vimrc"
alias src="source ENV/bin/activate"
alias note="cd /home/rr/Code/ACM_Notebook_new; cp ~/.vimrc.full ~/.vimrc"

# Tmux
alias tm="cp ~/.vimrc.full ~/.vimrc; tmux -2"
alias tmkill="tmux kill-session"

# Flush DNS, so that /etc/hosts is reloaded
alias flushdns="sudo /etc/init.d/nscd restart; sudo /etc/init.d/dns-clean start; sudo service network-manager restart"
# Reload audio
alias audio="pulseaudio -k && sudo alsa force-reload"

function update_release {
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);
    echo "current git branch: $CURRENT_BRANCH"
    g stash;
    g co master;
    g pull origin master;
    g co release;
    g pull origin release;
    g merge master;
    g push origin release;
    g co $CURRENT_BRANCH;
    g stash pop;
}
alias release=update_release
# live IPs:
# Backend:
# 122.11.129.30
# 122.11.129.4
#
# Webapi
# 122.11.129.5
# 122.11.129.9
# 203.117.172.187
# 122.11.129.38

alias proto='protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_db.proto; protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_cmd.proto;'
alias bproto='protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_db.proto; protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_cmd.proto; protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_mq.proto; protoc -I=bridge/protofile/ --python_out=bridge/protobuf/pb/ bridge/protofile/beeshop_search.proto;'
kill80() {
	sudo lsof -i :80 | grep 'apache2' | awk '{ print $2 }' | xargs sudo kill -9
	sudo lsof -i :80 | grep 'nginx' | awk '{ print $2 }' | xargs sudo kill -9
}

# Distributed GCJ stuff
alias dcj='/home/rr/Code/CF/DCJ/dcj_linux/dcj.sh'
alias dcc='function _dcc() { cp "$1/$1$2.h" "$1/$1.h"; dcj build --source="$1/$1.cpp" }; _dcc'
alias dcr='function _dcr() { dcj run --executable="$1/$1" --nodes=$2 --output=all }; _dcr'
# end of Distributed GCJ

alias ']'='xdg-open'
