cp ~/.aliases aliases
cp ~/.bash_profile bash_profile
cp ~/.bash_prompt bash_prompt
cp ~/.bashrc bashrc
cp ~/.curlrc curlrc
cp ~/.exports exports
cp ~/.extra extra
cp ~/.functions functions
cp ~/.osx osx
cp ~/.profile profile
cp ~/.screenrc screenrc
cp ~/.vimrc vimrc
cp ~/.gitconfig gitconfig
cp ~/codeforces.sh codeforces.sh
